### ISSUE TITLE
Possible issue installing obsmon 4.1.0 with R 4.1.1

### ISSUE THREAD

**Issue by isabelmonteiro** [Hirlam/obsmon#11]
I'm installing obsmon 4.1.0 Since the documentation recommends R >= 3.6.3, I updated my R to the latest available version: R 4.1.1. , I'm getting the following error while  running ./install 
Error: package 'argparse' was  installed before R 4.0.0: please re-install it

I uninstall R and remove all remaining arparse files from .libPaths() Next I reinstalled R and then updated argparse, the issue remains.
Do I have to install a specific R version and the install obsmon? If so what version should I use?

**Comment by paulovcmedeiros** [comment]
Hi @isabelmonteiro ,

Using R 4.1.0 with obsmon is fine. This is rather an R-related issue with packages compiled using different versions of the interpreter.

You say you've uninstalled and removed all argparse files from `.libPaths()`. Do you mean that you manually removed *all* `argparse*` directories located inside *all* the directories listed in `.libPaths()`? This is what I would suggest (regardless of obsmon, removing package directories located inside the directories listed in `.libPaths()` is probably a good idea after updating R). But if this is what you did, then I can of course look further. Just confirm this to me and then we'll take it from there :)

**Comment by isabelmonteiro** [comment]
Hi @paulovcmedeiros ,
that is what I did following a similar issue in 
https://stackoverflow.com/questions/24118558/complete-remove-and-reinstall-r-including-all-packages 

Isabel

**Comment by paulovcmedeiros** [comment]
Ok, thanks for the reply. Let's try the following then: Please go to your obsmon directory, run

`./install clean all`

and try installing again.

If that doesn't work, then run

`rm -rf utils/build/r_deps_installer/pkg_local_R-libs`

and retry.

Let me know if this helps and, if it does, if you needed to execute the  second command.

/Paulo.

**Comment by isabelmonteiro** [comment]
Thanks! 
./install clean all 
didn't work
Running 
rm -rf utils/build/r_deps_installer/pkg_local_R-libs
and then ./install again almost work... was able to install 146 R-libs, however was stopped in R-lib 80/146 :curl 
Please see att prit screen
![obsmon_install](https://user-images.githubusercontent.com/17830764/131654759-8a494e4f-586d-4e19-906a-145b1d3f3dc9.png)

**Comment by paulovcmedeiros** [comment]
Ok, progressing then.

Could you run the install script again, but this time as `./install --live-view-install-log` , and then attach it here?

The system should produce a logfile whenever install fails, but I can see from your screen print that the needed `.out` file could not be read at this time. Running the command as indicated above will cause the whole install log to be written to the screen.

**Comment by isabelmonteiro** [comment]
![obsmon_install2](https://user-images.githubusercontent.com/17830764/131668880-28f90eb5-94fc-47af-8b85-42cee51886e8.png)

**Comment by paulovcmedeiros** [comment]
This time you seem to be missing a system dependency, outside of obsmon. Try to install in your system the package suggested under the `ANTICONF ERROR` message (choose the one appropriate for your case), and then run obsmon's install script again.

Let me know how it goes.

**Comment by isabelmonteiro** [comment]
It went ok (apart some packages I had to install manually), however after one of these installations Cairo:
apt-get-install libcairo-dev2
got the following log 
![obsmon_install3](https://user-images.githubusercontent.com/17830764/131709050-8f715f36-d82b-4fd9-9397-9eb769813d0d.png)
(from ./install -live-install log

**Comment by paulovcmedeiros** [comment]
I think this is not really related to obsmon itself, but, again, due to some missing system dependency.

Could you go to your `$HOME` directory, open `R`, run

`install.packages('Cairo')`

and tell me what happens? I suspect you'll get the same error.

**Comment by paulovcmedeiros** [comment]
Just as an addition to my previous message: It seems the missing system dependency is `libxt-dev`. If the `install.packages('Cairo')` command I suggested in the previous message also fails, then you can install the sys dep `libxt-dev` and try running obsmon's install script again. Let me know how it goes.

**Comment by isabelmonteiro** [comment]
Installing libxt-dev and then Cairo, worked, but then something funny happen, I successfully installed obsmon (see below) but a package didn't worked, I install it, and went OK .
![obsmon_install4](https://user-images.githubusercontent.com/17830764/131831448-b1760933-ef61-48cc-b8cd-4fe459bdf6d9.png)

**Comment by isabelmonteiro** [comment]
and also with DBI,

**Comment by paulovcmedeiros** [comment]
Hi @isabelmonteiro ,

My test in your `$HOME` was merely to assert that something extra needed to be installed in your system before you could installed the `Cairo` R-lib. You should however not install anything there if your aim is to use it with obsmon, as obsmon uses its own environment.

Before we can proceed, please remove any library that you installed manually with the intent of using it with obsmon. Then ,*from inside obsmon's own directory*, run

`./install clean && ./install`

If another problem occurs, then we'll take it from there. But, again, please do not install packages in your `$HOME` if your aim is to use them with obsmon. Otherwise it can be difficult for me to help, as the install would then happen out of obsmon's environment and I won't have control over it.

**Comment by isabelmonteiro** [comment]
Hi Paulo,
Sorry ...
![obsmon_install6](https://user-images.githubusercontent.com/17830764/131847201-ee80c66c-b8f1-4343-a1fb-08b5003c7258.png)

Just following your instructions : 
got the following

**Comment by paulovcmedeiros** [comment]
I just noticed that:

1. There's a `*-dirty` tag in the code's version tag
2. The usual obsmon local R-lib search path (`.installer_local_R-libs/R-libs`) is not being shown under `Looking for R-libs in the following directories`

Can you send me the results of `git diff`? I suspect that some of the obsmon's files were changed in a way that made it blind to the local R-lib directory.

**Comment by isabelmonteiro** [comment]
![obsmon_install6](https://user-images.githubusercontent.com/17830764/131849028-84f63ab5-d3ac-4197-ae3d-69e97faaedb8.png)

**Comment by paulovcmedeiros** [comment]
Ok, as I suspected: The `.Rprofile` file was changed.

You should ideally not change any obsmon file when troubleshooting (unless I ask you to do so, of course), otherwise things get out of my reach. This is especially important for the `.Rprofile` file, as this is **the** file that controls where obsmon should look for R-libs. This is why you've been getting the strange behaviour of things being installed but not found.

Please run

```
git checkout .Rprofile
./install clean
./install
```

and then let me know how it goes.

**Comment by isabelmonteiro** [comment]
![obsmon_install6](https://user-images.githubusercontent.com/17830764/131854571-5ff891fd-dbd2-4a99-84e5-d64e00fc4ace.png)

**Comment by paulovcmedeiros** [comment]
So installation worked. Does it work fine when you set your browser to `http://127.0.0.1:5391` ?
The warning messages shouldn't affect the way the code works.

**Comment by isabelmonteiro** [comment]
Yes installation worked
I had to install firefox, but I'm not able to set my browser to http://127.0.0.1:5391
am I doing something wrong? should I install another browser ?

**Comment by paulovcmedeiros** [comment]
This `http://127.0.0.1:5391` is just an address pointing to a port in your local host (your own computer). Is obsmon still running listening on that address?

You may want to try `./obsmon --launch` which will launch your default browser and point it to the appropriate address automatically. How does it go?

**Comment by isabelmonteiro** [comment]
Yes I understand. I tried both ./ obsmon --launch and ./obsmon and copy past the mentioned ip address in both cases I get a msdg Gah Your tab just crash.
Apart from a warning message I also get a failed to create bus connection( see print screen above) when I run obsmon, Is this not important as well?

**Comment by paulovcmedeiros** [comment]
I'm not sure this problem is related to obsmon... Just in case: Have you tried turning your computer off and on again? (no IT Crowd pun intended :) )

**Comment by isabelmonteiro** [comment]
Yes, I did the on and off  solution ;)
It is not indeed related with obsmon. I have 16.04.7 and this dbus issue is a problem (a google search show that). It is not so easy to solve because I'm not able to update my ubuntu. But you are right it is not an obsmon issue

**Comment by paulovcmedeiros** [comment]
Ok, thanks for the update then :)

I suggest you try to catch your IT guys then for this. Seems like a problem that can affect many other things in your workflow, so they probably will give it some priority.

I'll close this issue then since I think we've covered the obsmon issue. Thanks for reporting this and, of course, feel free to reopen it should you find that the obsmon part of the problem hasn't actually been solved.
