### ISSUE TITLE
Station identifier and codetype filter for maps/statistics

### ISSUE THREAD

**Issue by ewhelan** [Hirlam/obsmon#2]
A filter for data by identifier/codetype for maps/statistics would be nice. Request for menu option.

From [https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics](https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics)

**Comment by paulovcmedeiros** [comment]
Done in obsmon v4.1.0. Not only the station picker field was made searchable, but most other fields too (wherever applicable).
