### ISSUE TITLE
Default map settings

### ISSUE THREAD

**Issue by ewhelan** [Hirlam/obsmon#21]
Hi @paulovcmedeiros 

I am looking at some data coverage plots in 4.2 and have a question ...

I have defined my Harmonie domain - it works beautifully. Thanks! However, the default map centre seems to be shifted too far south. See attached screen-shot. Can you suggest and changes that might fix this?

@ewhelan 
![Screenshot from 2022-01-31 16-02-27](https://user-images.githubusercontent.com/17612201/151829329-023fde0e-98f8-4a29-8cd3-c6ba2f6cf9c1.png)

**Comment by paulovcmedeiros** [comment]
Done :)
