### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by roger-randria** [Hirlam/obsmon#22]
1) I have a problem when trying to install the newest version of obsmon. I get the following error:
./install
Error in isFALSE(args$versions_file) : could not find function "isFALSE"
Calls: source ... .sourceNeededFiles -> source -> withVisible -> eval -> eval
Execution halted

This is what I have on this machine:
R --version
R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

Thanks in advance

**Comment by paulovcmedeiros** [comment]
Hi Roger,

This one is easy: Obsmon requires `R >= 4.0.5` (see the "Installing, executing and updating" section in the docs). This function didn't exist in earlier versions of R.

The solution is to update the version of the R interpreter that you are using.
