### ISSUE TITLE
Request to make colour scale and data range editable on plots

### ISSUE THREAD

**Issue by ewhelan** [Hirlam/obsmon#3]
Request to make colour scale and data range editable on plots

From [https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics](https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics)

**Comment by paulovcmedeiros** [comment]
Done. Available from obsmon v4.1.0.
