### ISSUE TITLE
Request for hPa instead of Pa on vertical profiles

### ISSUE THREAD

**Issue by ewhelan** [Hirlam/obsmon#4]
Request for hPa instead of Pa on vertical profiles

From [https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics](https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics)

**Comment by paulovcmedeiros** [comment]
This is a special case of what was requested #5 and is now done as a result of implementing that request.
