### ISSUE TITLE
Variable units on plots

### ISSUE THREAD

**Issue by ewhelan** [Hirlam/obsmon#5]
Request for variable units on plots

From [https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics](https://hirlam.org/trac/wiki/Meetings/HarmonieWorkingWeek/UseofObsandALGO202010/Day2Diagnostics)

**Comment by paulovcmedeiros** [comment]
Done. This has been made available in obsmon v4.1.0.
